### ISSUE TITLE
screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gases-intro#2]
@arouinfar what would you like to do for screen icons?  Since both screens are derivatives of the _Ideal_ screen from Gas Properties, they both currently have the same icon.  See below.

<img width="755" alt="screenshot_1229" src="https://user-images.githubusercontent.com/3046552/58899224-9e096b80-86b9-11e9-97e5-ca265662ff64.png">

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet I think the Ideal screen icon works well for Laws, but we'll need to find an alternative for Intro.

What would you think about doing something abstract like a  few gas particles?
<img src="https://user-images.githubusercontent.com/8419308/58972193-37985200-877a-11e9-8b08-96f63b852b5d.png" width=300>  <img src="https://user-images.githubusercontent.com/8419308/58972193-37985200-877a-11e9-8b08-96f63b852b5d.png" width=75>

**Comment by ariel-phet** [comment]
That works well for me, I might add a few more particles for the intro icon, but also probably fine the way it is. (i was looking at the phase changes icon in SOM, and it has a fair number more particles and looks OK). For the ideal, I might also consider making the iconic particles more and a bit smaller, but also OK with it being a bit more cartoonish. KP seemed happy with the icons for the main sim, so I suppose probably wise not to deviate far. 

The summary being, looks good, feel free to take or leave suggestions above, and I trust your call @arouinfar

**Comment by pixelzoom** [comment]
_Intro_ icons has been implemented in master, see screenshots below.  Looks good to me. @arouinfar please review.

<img width="890" alt="screenshot_1234" src="https://user-images.githubusercontent.com/3046552/58981618-eeeb9380-878f-11e9-9908-04caedfcf665.png">

<img width="366" alt="screenshot_1235" src="https://user-images.githubusercontent.com/3046552/58981638-fa3ebf00-878f-11e9-8ced-637a9595b120.png">

**Comment by pixelzoom** [comment]
Slight adjustment to particle locations in the above commit. 

<img width="846" alt="screenshot_1236" src="https://user-images.githubusercontent.com/3046552/58984516-818f3100-8796-11e9-9365-6edca6b7c2f8.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom looks good to me.

@ariel-phet I like the cartoonish look of the larger particles. For consistency, I think it's nice to keep things the same as `gas-properties` and the particle size similar between screens.
