### ISSUE TITLE
Set pressureNoise to false by default

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gases-intro#3]
In https://github.com/phetsims/gas-properties/issues/92#issuecomment-497458395 we decided to make `pressureNoise` a boolean and add a checkbox to the Options dialog, partly due to this sim.

In https://github.com/phetsims/gas-properties/issues/100 we forgot to specify the value of `pressureNoise` so assigning @pixelzoom to set the default to `false`.

**Comment by pixelzoom** [comment]
This was an interesting problem to solve -- how to override a default query parameter value in a derivative sim.  My solution (see above commit) is to use the query parameter value if it's provided in the URL, otherwise set to false. 

@arouinfar back to you for review in master.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
