### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gases-intro#5]
For https://github.com/phetsims/QA/issues/388 and #1 
This sim is being published for the first time, and so it needs screenshots and alt screenshots.  @arouinfar let me know what you would like them to look like and when you think the sim is settle enough to take them, then assign back to me.

**Comment by arouinfar** [comment]
@KatieWoe please take screenshots during rc.2.

### Main screenshot
![Gas Properties-1](https://user-images.githubusercontent.com/8419308/62252404-fbffba00-b3af-11e9-8574-9f8abc4a13ba.png)

### Alt 1
<img width="1440" alt="Gas Properties-2" src="https://user-images.githubusercontent.com/8419308/62252405-fbffba00-b3af-11e9-9afa-2ae28fd2716b.png">

### Alt 2
Use equal numbers of light and heavy particles.
![Gas Properties-3](https://user-images.githubusercontent.com/8419308/62252406-fbffba00-b3af-11e9-9753-c2fe559511db.png)

### Alt 3
Use particles with different radii, and take screenshot as they start to mix.
![Gas Properties-4](https://user-images.githubusercontent.com/8419308/62252407-fc985080-b3af-11e9-93ab-aa6366a939bb.png)

**Comment by arouinfar** [comment]
@KatieWoe please take the screenshots in rc.2

### Main screenshot
![Gases Intro 1](https://user-images.githubusercontent.com/8419308/62255154-42a5e200-b3b9-11e9-9336-88c2dff16fb7.png)

### Alt 1
Take the screenshot just after injecting a 150 light particles.
<img width="1440" alt="Gases Intro 3" src="https://user-images.githubusercontent.com/8419308/62255156-42a5e200-b3b9-11e9-9652-a6f63125fcf6.png">

### Alt 2
![Gases Intro 2](https://user-images.githubusercontent.com/8419308/62255155-42a5e200-b3b9-11e9-82b4-c5060eed36bf.png)

**Comment by KatieWoe** [comment]
Here are the screenshots for this sim:
![gases-intro-screenshot](https://user-images.githubusercontent.com/41024075/62327522-18fac280-b46e-11e9-998b-b1c4486c675f.png)
<img width="768" alt="gases-intro-screenshot-alt1" src="https://user-images.githubusercontent.com/41024075/62327523-18fac280-b46e-11e9-979f-25b602bfdabc.png">
![gases-intro-screenshot-alt2](https://user-images.githubusercontent.com/41024075/62327524-18fac280-b46e-11e9-8f99-dd8727953fda.png)

**Comment by KatieWoe** [comment]
@arouinfar to approve

**Comment by arouinfar** [comment]
Looks good!

**Comment by KatieWoe** [comment]
Screenshots done.  Closing
